### ISSUE TITLE
meeting logistics

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/Workshops#8]
- [x] reserve space at NCGR
- [x] reserve block of rooms at hotel
- [x] arrange transportation
- [x] develop plan for meals
- [x] work out details for how to reimburse participants with ISU involvement

**Comment by adf-ncgr** [comment]
@joelb123 gets the credit for handling all of this. might be worth documenting any lessons learned either here or somewhere else before we close this out, but will leave that up to him.

**Comment by joelb123** [comment]
Wrote logistics.rst with all the thoughts on the topic that I had.
